---

  time_intervals:
    send_ships_for_work: 5
    verify_lost_fight: 1
    confirm_win: 1
    check_for_login: 1
    interval_between_moviments: 1

  threshold:
    default: 0.7
    commom: 0.8
    select_wallet_buttons: 0.8

  scroll_size: 60
  empty_scroll_attemps: 8
  use_click_and_drag_instead_of_scroll: true
  click_and_drag_amount: 100
  